# -*- coding: utf-8 -*-
"""hackathon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJ2GvZpBGFESv7MNxFGN_Y6IBjoGxLzC
"""

#Upload Files
from google.colab import files
uploaded = files.upload()

#Load CSV
import pandas as pd

orders = pd.read_csv("orders.csv")
orders.head()

#Load JSON
users = pd.read_json("users.json")
users.head()

#Load SQL
import sqlite3

conn = sqlite3.connect("restaurants.db")

with open("restaurants.sql", "r") as f:
    sql_script = f.read()

conn.executescript(sql_script)

restaurants = pd.read_sql("SELECT * FROM restaurants", conn)
restaurants.head()

#Merge the Datasets (LEFT JOINS)
orders_users = pd.merge(
    orders,
    users,
    on="user_id",
    how="left"
)

final_df = pd.merge(
    orders_users,
    restaurants,
    on="restaurant_id",
    how="left"
)

#Final Dataset Validation
final_df.info()

final_df.head()

#Save
final_df.to_csv("final_food_delivery_dataset.csv", index=False)

#Download Final Output
files.download("final_food_delivery_dataset.csv")

"""MCQs"""

##1
gold_city_revenue = (
    final_df[final_df["membership"] == "Gold"]
    .groupby("city")["total_amount"]
    .sum()
    .sort_values(ascending=False)
)

gold_city_revenue

##2
final_df.groupby("cuisine")["total_amount"].mean().sort_values(ascending=False)

##3
high_value_users = (
    final_df.groupby("user_id")["total_amount"]
    .sum()
    .reset_index()
)

(high_value_users["total_amount"] > 1000).sum()

##4
bins = [0, 3.5, 4.0, 4.5, 5.0]
labels = ["3.0–3.5", "3.6–4.0", "4.1–4.5", "4.6–5.0"]

final_df["rating_range"] = pd.cut(final_df["rating"], bins=bins, labels=labels)

final_df.groupby("rating_range")["total_amount"].sum().sort_values(ascending=False)

##5
final_df[final_df["membership"] == "Gold"] \
    .groupby("city")["total_amount"] \
    .mean() \
    .sort_values(ascending=False)

##6
final_df.groupby("cuisine").agg(
    restaurant_count=("restaurant_id", "nunique"),
    revenue=("total_amount", "sum")
).sort_values("restaurant_count")

##7
gold_pct = (
    final_df[final_df["membership"] == "Gold"].shape[0]
    / final_df.shape[0]
) * 100

round(gold_pct)

##8
final_df.columns

##8
restaurant_stats = final_df.groupby("name").agg(
    avg_order_value=("total_amount", "mean"),
    order_count=("order_id", "count")
)

restaurant_stats[restaurant_stats["order_count"] < 20] \
    .sort_values("avg_order_value", ascending=False) \
    .head()

##8
restaurant_stats = final_df.groupby("restaurant_id").agg(
    avg_order_value=("total_amount", "mean"),
    order_count=("order_id", "count")
)

restaurant_stats[restaurant_stats["order_count"] < 20] \
    .sort_values("avg_order_value", ascending=False) \
    .head()

##8
gold_city_revenue = (
    final_df[final_df["membership"] == "Gold"]
    .groupby("city")["total_amount"]
    .sum()
)

top_city = gold_city_revenue.idxmax()

final_df[
    (final_df["membership"] == "Gold") &
    (final_df["city"] == top_city)
].shape[0]

##9
final_df.groupby(["membership", "cuisine"])["total_amount"] \
    .sum() \
    .sort_values(ascending=False)

##10
final_df["order_date"] = pd.to_datetime(final_df["order_date"])
final_df["quarter"] = final_df["order_date"].dt.to_period("Q")

final_df.groupby("quarter")["total_amount"].sum().sort_values(ascending=False)

"""NUMERICALS

"""

##1
final_df[final_df["membership"] == "Gold"].shape[0]

##2
round(final_df[final_df["city"] == "Hyderabad"]["total_amount"].sum())

##3
final_df["user_id"].nunique()

##4
round(
    final_df[final_df["membership"] == "Gold"]["total_amount"].mean(), 2
)

##5
final_df[final_df["rating"] >= 4.5].shape[0]

##6
top_city = gold_city_revenue.idxmax()
final_df[
    (final_df["membership"] == "Gold") &
    (final_df["city"] == top_city)
].shape[0]